
version: '3.8'

services:
  bssci-service-center:
    build: .
    container_name: bssci-service-center
    init: true
    ports:
      - "16019:16018"  # TLS Server port
      - "5056:5000"    # Web UI port
    volumes:
      # Use absolute paths and specific Synology volume syntax
      - type: bind
        source: ./certs
        target: /app/certs
        read_only: true
      - type: bind
        source: ./endpoints.json
        target: /app/endpoints.json
        bind:
          create_host_path: true
      - type: bind
        source: ./bssci_config.py
        target: /app/bssci_config.py
        bind:
          create_host_path: true
      - type: bind
        source: ./logs
        target: /app/logs
        bind:
          create_host_path: true
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - SYNOLOGY_DOCKER=1
    networks:
      - bssci-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Run as root to ensure file access
    user: "0:0"
    cap_add:
      - CHOWN
      - FOWNER
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s1 = socket.create_connection(('localhost', 16018), timeout=5); s2 = socket.create_connection(('localhost', 5000), timeout=5); s1.close(); s2.close()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  bssci-network:
    driver: bridge
