version: '3.8'

services:
  bssci-service-center:
    build: .
    container_name: bssci-service-center
    init: true
    ports:
      - "16019:16018"  # TLS Server port
      - "5056:5000"    # Web UI port
    volumes:
      # Use Synology-compatible volume mounts
      - ./certs:/app/certs:ro
      - ./logs:/app/logs:rw
      # Copy config files to container-writable locations
      - ./endpoints.json:/tmp/host_endpoints.json:ro
      - ./bssci_config.py:/tmp/host_bssci_config.py:ro
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - SYNOLOGY_DOCKER=1
      - PUID=1000
      - PGID=1000
    networks:
      - bssci-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Run as root initially to handle file setup
    user: "0:0"
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s1 = socket.create_connection(('localhost', 16018), timeout=5); s2 = socket.create_connection(('localhost', 5000), timeout=5); s1.close(); s2.close()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  bssci-network:
    driver: bridge