
version: '3.8'

services:
  bssci-service-center:
    build: .
    container_name: bssci-service-center
    ports:
      - "16019:16017"
    volumes:
      - ./certs:/app/certs:ro
      - ./endpoints.json:/app/endpoints.json
      - ./bssci_config.py:/app/bssci_config.py
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - bssci-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; socket.create_connection(('localhost', 16017), timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  bssci-network:
    driver: bridge
