
[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "aiomqtt>=2.4.0",
    "black>=25.1.0",
    "flake8>=7.3.0",
    "flask>=3.1.2",
    "msgpack>=1.1.1",
]
